---
title: "Production & LC vs Capitals - BrazilAgriAnalysis"
author: "James D.A. Millington"
date: "August 2018"
output: 
  html_document: 
    keep_md: yes
    code_folding: hide
    df_print: paged
---


```{r results='hide', warning=F, message=F}

rm(list=ls())
library(tidyverse)
library(readxl)

```



Scatter plots of observed lc vs capitals




Scatter plots of observed production vs capitals






#Distributions
What is the distribution of production (Munis) for each commodity? Where is the median? Examining these will help to understand what the shapes of production curves should be...


Meat
```{r}

#d <- dairy_prod_Amunis %>% gather(key = year, value = dairy, -muniID, -state)

mt <- meat_prod_Astates_long %>% 
  filter(!is.na(meat_gg)) %>%
  group_by(year) %>% 
  summarise(mx = max(meat_gg), md = median(meat_gg), mn = mean(meat_gg), sd = sd(meat_gg))  

mt  

meat_prod_Astates_long %>% 
  filter(meat_gg > 0) %>%
  select(-state) %>%
  ggplot(aes(x = meat_gg, colour = year)) +
  geom_freqpoly(binwidth = 100)

meat_prod_Astates_long %>% 
  filter(meat_gg > 0) %>%
  ggplot(aes(x = meat_gg, colour = year)) +
  stat_ecdf()


```

Dairy
```{r}

d <- dairy_prod_Amunis %>% gather(key = year, value = dairy, -muniID, -state)

dt <- d %>% 
  filter(!is.na(dairy)) %>%
  group_by(year) %>% 
  summarise(mx = max(dairy), md = median(dairy), mn = mean(dairy), sd = sd(dairy), md_scaled = round( median(dairy) / max(dairy), 3), mn_scaled = round(mean(dairy) / max(dairy),3) )  

dt  

d %>% 
  filter(dairy < 20000) %>%
  ggplot(aes(x = dairy, colour = year)) +
  geom_freqpoly(binwidth = 1000)

d %>% 
  filter(dairy < 20000) %>%
  ggplot(aes(x = dairy, colour = year)) +
  stat_ecdf()


```


Soy
```{r}

d <- soy_prod_Amunis %>% gather(key = year, value = soy, -muniID, -state)

dt <- d %>% 
  filter(!is.na(soy)) %>%
  group_by(year) %>% 
  summarise(mx = max(soy), md = median(soy), mn = mean(soy), sd = sd(soy))  

dt  

d %>% 
  filter(soy < 1000000) %>%
  ggplot(aes(x = soy, colour = year)) +
  geom_freqpoly(binwidth = 10000)

d %>% 
  filter(soy < 1000000) %>%
  ggplot(aes(x = soy, colour = year)) +
  stat_ecdf()


```


Maize
```{r}

ma <- maize_prod_Amunis %>% gather(key = year, value = maize, -muniID, -state)

mat <- ma %>% 
  filter(!is.na(maize)) %>%
  group_by(year) %>% 
  summarise(mx = max(maize), md = median(maize), mn = mean(maize), sd = sd(maize))  

mat  

ma %>% 
  filter(maize < 100000) %>%
  ggplot(aes(x = maize, colour = year)) +
  geom_freqpoly(binwidth = 1000)

ma %>% 
  filter(maize < 100000) %>%
  ggplot(aes(x = maize, colour = year)) +
  stat_ecdf()


```